Separate followups and registrations
simpledotorg/simple-server pull request #1356
Opened 2020-09-25 12:23 UTC by harimohanraj89

**Story card:** TBD

## Because

It is confusing to have assigned follow-up info right next to registration info in the same table.

## This addresses

* Separate followups and registrations into two separate tables in:
  * District analytics report
  * District new report - Details page

While we're in here, we make a few other enhancements:
* Allow more than one sortable table on a single page
* Consistent-ize our month format across the board to `Mon-YYYY`
* Consistent-ize our quarter format across the board to `QX YYYY`
* Fix a table sorting bug on the Missed Visits page - Total column

## Screenshots

### Before

<img width="949" alt="Screen Shot 2020-09-25 at 5 52 39 PM" src="https://user-images.githubusercontent.com/4241399/94266594-fec85180-ff57-11ea-9796-f3963e1b43ec.png">
<img width="940" alt="Screen Shot 2020-09-25 at 5 53 01 PM" src="https://user-images.githubusercontent.com/4241399/94266605-025bd880-ff58-11ea-8768-aef196ac7b9b.png">

### After

<img width="943" alt="Screen Shot 2020-09-25 at 5 52 17 PM" src="https://user-images.githubusercontent.com/4241399/94266606-02f46f00-ff58-11ea-8c02-6f4a07d792d5.png">
<img width="937" alt="Screen Shot 2020-09-25 at 5 52 31 PM" src="https://user-images.githubusercontent.com/4241399/94266615-04be3280-ff58-11ea-9d02-7467205ce03d.png">

2020-09-25 13:17 UTC, claudiovallejo commented on app/helpers/quarter_helper.rb
> +    "Q#{quarter}-#{year}"
@harimohanraj89 added the hyphen to the quarter string. Did a quick check, and don't think this breaks any tests.

2020-09-28 08:09 UTC, prabhanshuguptagit requested changes

2020-09-28 08:09 UTC, prabhanshuguptagit commented on app/views/analytics/districts/_follow_ups_table.html.erb
> +          <th class="row-label sort-label" <%= "data-sort-default" if index == 5 %> data-sort-method="number">
[nit] How about
```
if date == dates.last
```

2020-09-29 11:59 UTC, claudiovallejo approved these changes

2020-09-29 12:07 UTC, harimohanraj89 commented on app/views/analytics/districts/_follow_ups_table.html.erb
> +          <th class="row-label sort-label" <%= "data-sort-default" if index == 5 %> data-sort-method="number">
Love it.

2020-09-29 12:07 UTC, harimohanraj89 commented on app/views/analytics/districts/_registrations_table.html.erb
> +<div class="card mt-0 pr-0 pr-md-3">
We considered it :) We're gonna wait until someone asks for it.

2020-09-29 12:33 UTC, prabhanshuguptagit approved these changes
✨

2020-09-29 19:42 UTC, merged