Manage zones in facility groups
simpledotorg/simple-server pull request #1500
Opened 2020-11-05 12:30 UTC by prabhanshuguptagit

**Story card:** [ch1867](https://app.clubhouse.io/simpledotorg/story/1867/create-a-ui-to-manage-blocks-in-facility-groups)

## Because

We are making zones a first class entity via Region which are populated in a dropdown in the Facility form. A dashboard user should be able to create and update these blocks for a facility group.

## This addresses

This adds a UI in the Facility Group form to manage block-regions under the FG.

![image](https://user-images.githubusercontent.com/16774200/98241293-beb1b100-1f90-11eb-9a1a-8729c495d63e.png)

2020-11-06 14:50 UTC, rsanheim requested changes

2020-11-06 14:50 UTC, rsanheim commented on app/models/facility_group.rb
> +  end
I'm concerned about using callbacks for this.  This seems like something better handled by the controller when blocks are added or removed.

2020-11-12 14:26 UTC, rsanheim commented on app/controllers/admin/facility_groups_controller.rb
> +      update_block_regions if Flipper.enabled?(:regions_prep)
We gotta handle the case where the update fails from the update_block_regions here - probably want to wrap the whole thing in a transaction?

2020-11-13 11:04 UTC, kitallis approved these changes
Left some comments, mostly looks good. Let's merge this quickly to unblock other PRs.

2020-11-13 11:18 UTC, prabhanshuguptagit commented on app/controllers/admin/facilities_controller.rb
> +    @available_zones = @facility_group.region&.blocks&.order(:name)&.pluck(:name) || []
The conditionals are redundant since it's `facility_group.region` should exist once this is enabled. Removed.

2020-11-13 11:18 UTC, prabhanshuguptagit commented on app/controllers/admin/facility_groups_controller.rb
> +  def enable_diabetes_management
Removed.

2020-11-13 11:58 UTC, merged