2890 add assigned patients to progress tab
simpledotorg/simple-server pull request #2143
Opened 2021-03-11 19:00 UTC by kpethtel

**Story card:** [ch2890](https://app.clubhouse.io/simpledotorg/story/2890/add-total-assigned-patients-to-progress-bar-web-view)

## Because

We want to display the total assigned patients to the user in the android app. 

## This addresses

## Test instructions

Enter detailed instructions for how to test this PR...

2021-03-12 13:00 UTC, harimohanraj89 requested changes
Some suggestions from me!

2021-03-12 15:13 UTC, kpethtel commented on app/views/api/v3/analytics/user_analytics/show.html.erb
> +    <p class="assigned-count"><%= @user_analytics.current_facility.assigned_hypertension_patients.count %></p>
Will do.

2021-03-12 15:13 UTC, kpethtel commented on app/views/api/v3/analytics/user_analytics/show.html.erb
> +    <p class="assigned-label"> <%= t("analytics.assigned_patients_label") %></p>
Will do.

2021-03-12 22:50 UTC, rsanheim approved these changes
LGTM

2021-03-16 11:04 UTC, harimohanraj89 approved these changes
:shipit:

2021-03-19 16:47 UTC, kpethtel commented
> :shipit:

Actually, this got put on ice for now. What should I do with this @claudiovallejo ?

2021-03-19 16:49 UTC, claudiovallejo commented
> > :shipit:
> 
> 
> 
> Actually, this got put on ice for now. What should I do with this @claudiovallejo ?

Updated designs for the progress tab won't be ready for another 1 - 2 weeks. Not sure if it's best to close this PR for now and reopen later @kpethtel?

2021-03-19 17:00 UTC, closed without merging