Add ADR for block level sync
simpledotorg/simple-server pull request #2439
Opened 2021-04-20 08:58 UTC by prabhanshuguptagit

**Story card:** [ch3265](https://app.clubhouse.io/simpledotorg/story/3265/add-adr-for-block-level-sync-flexible-sync-radius)

## Because

## This addresses

2021-04-22 07:43 UTC, ssrihari reviewed
👌  glad you took the time to write this down @prabhanshuguptagit

2021-04-22 07:43 UTC, ssrihari commented on doc/arch/014-region-level-sync.md
> +_This ADR has been added retroactively in Apr 2021 to capture our switch to block-level syncing._
This is essentially the status section. Perhaps we can move that up here and coalesce with this part.

2021-04-22 07:43 UTC, ssrihari commented on doc/arch/014-region-level-sync.md
> +The slowdown was correlated to the volume of patient data synced to the user’s phone. We realised that the amount of data being stored on the device had to be reduced for better long-term performance
> correlated

Should we say it was _caused_ by it?

2021-04-22 07:43 UTC, ssrihari commented on doc/arch/014-region-level-sync.md
> +Currently we sync the entire district's records to a user's phone. Some of the large districts have upto 50,000 patients, which can amount to 400-500 MB of data.
Is there a target storage volume (or a range) on the device at which the app performs optimally? We should ideally have that.

2021-04-22 07:43 UTC, ssrihari commented on doc/arch/014-region-level-sync.md
> +This means that we can sync only a block's data to the user's phone and be reasonably confident about finding patients on the app.
> we found that patients rarely move between facilities across blocks

We have an average of ~600 duplicates across blocks per month in the last few months. Is this still what we would consider rare? Perhaps we should consider rewording accordingly.

2021-04-22 07:43 UTC, ssrihari commented on doc/arch/014-region-level-sync.md
> +- When a patient gets registered across blocks as a duplicate, we will need to identify them and merge their data.
Should we also add that we plan to implement online patient lookup to account for the cases in which local lookup fails?

2021-04-22 07:43 UTC, ssrihari commented on doc/arch/014-region-level-sync.md
> +## Context
If there's a PRD, we should link to it.

2021-04-22 07:43 UTC, ssrihari commented on doc/arch/014-region-level-sync.md
> +    - The duplicate patient records will be merged by the Simple team later.
How was the move to block sync managed end to end?

1. How is the change in sync region detected on the app?
2. How do we remove the previous block's data on the app when the change happens?
3. How do we ensure that all data is synced before removal?
4. How did we plan for resource utilisation increase on the backend to accommodate full syncs?

This is important context that will be useful the next time we decide to change the sync region.

2021-04-22 07:43 UTC, ssrihari commented on doc/arch/014-region-level-sync.md
> +    - The duplicate patient records will be merged by the Simple team later.
Ah, I see most of this was captured in the wiki 😅 . Very cool. I think only 3 is unanswered. Would be good to go into some detail overall therein. If there's a related android ADR, would be super relevant to link to it.

2021-04-22 09:14 UTC, harimohanraj89 requested changes
My thoughts.

2021-05-03 10:28 UTC, prabhanshuguptagit commented on doc/arch/014-region-level-sync.md
> +  This is introduced through the `Region` model.
Yes

2021-05-03 10:29 UTC, prabhanshuguptagit commented on doc/wiki/adjusting-sync-boundaries.md
> +  The criteria for selecting these patients is currently defined [in the Region model](https://github.com/simpledotorg/simple-server/blob/5a6416760e016a2ba2d12f46e46135d11927497c/app/models/region.rb
This is the only place, other than the PRD.

2021-05-03 11:36 UTC, harimohanraj89 approved these changes
My feedback is addressed 🚀

2021-05-03 13:19 UTC, merged