Start a CODEOWNERS files for request review on reporting queries
simpledotorg/simple-server pull request #2467
Opened 2021-05-05 02:56 UTC by rsanheim

This adds a CODEOWNERS file that should request review from @claudiovallejo for any changes to the `app/queries` directory. This is covers the reporting queries, as well as other unrelated queries...which isn't perfect but I think that's fine to start as see how this works. 

See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
for docs and examples

2021-05-05 18:38 UTC, claudiovallejo approved these changes
Thanks for doing this @rsanheim!!

2021-05-06 05:43 UTC, harimohanraj89 requested changes

2021-05-06 05:43 UTC, harimohanraj89 commented on .github/CODEOWNERS
> +/app/queries/ @@claudiovallejo
`@claudiovallejo`, single `@`?

2021-05-06 05:52 UTC, harimohanraj89 commented
@rsanheim I've added myself to `/config/data/medications.yml` as discussed [here](https://github.com/simpledotorg/simple-server/pull/2456#discussion_r626453872).

2021-05-07 09:15 UTC, harimohanraj89 approved these changes

2021-05-07 18:52 UTC, merged