Download drug consumption report as CSV
simpledotorg/simple-server pull request #2563
Opened 2021-06-01 14:46 UTC by prabhanshuguptagit

**Story card:** [ch3624](https://app.clubhouse.io/simpledotorg/story/3624/allow-downloading-drug-consumption-report)

## Because

Drug consumption reports to be downloaded as a CSV.

## This addresses

Adds: /my_facilities/drug_consumption/download.csv

2021-06-03 11:05 UTC, harimohanraj89 requested changes
Some minor feedback. The CSV generation is a bit cumbersome, but it's very clear what's going on. I took a stab at massaging the `@drugs_by_category` into a data structure that would be more easily cast to CSV, but the dynamic nature of categories and drugs makes it a little hard.

2021-06-08 12:14 UTC, prabhanshuguptagit commented on app/exporters/drug_consumption_report_exporter.rb
> +          consumed
The HTML view does some fancy styling on top, extracted this to a method in the exporter.

2021-06-08 12:35 UTC, prabhanshuguptagit commented on app/controllers/my_facilities/drug_stocks_controller.rb
> +  end
Added in 85bd94b

2021-06-10 05:31 UTC, harimohanraj89 approved these changes
Godspeed

2021-06-10 09:30 UTC, merged