3406 ab testing architecture docs
simpledotorg/simple-server pull request #2586
Opened 2021-06-08 15:29 UTC by kpethtel

**Story card:** [ch3406](https://app.clubhouse.io/simpledotorg/story/3406/write-architecture-doc)

## Because

This is an attempt to document the A/B framework. The ticket also calls for diagrams, but I'm going to have to defer that for a future ticket.

2021-06-15 22:06 UTC, rsanheim requested changes
Hey this is a good start.  Overall I think its a bit too low level for an ADR, and could use some clean up so that it focuses more on the long term implications of moving to an AB testing approach for our notifications.

I left some comments around things to remove and some stuff to expand on, lemme know if you'd like to discuss further!

2021-06-15 22:06 UTC, rsanheim commented on doc/arch/016-ab-testing.md
> +That doesn't make sense for patients who do not have upcoming appointments. Messages for stale patients will start on the same day the patient is added to the experiment. There are many patients who
```suggestion
Messaging for stale patients will run on a continual daily basis during the experiment. This is to stagger the messages over the experiment time so as to not overwhelm clinics with many patients coming to a clinic on the same day.  We will add a random batch of stale patients per day (currently 10,000) to the experiment and schedule them based on the messaging templates configured in the experiment.
```

2021-06-15 22:06 UTC, rsanheim commented on doc/arch/016-ab-testing.md
> +In both types of experiments, patients will be randomly placed into treatment groups. Treatment groups will define the message texts, number of messages, and when to send the messages. Test patients
```suggestion
In both types of experiments, patients will be randomly placed into treatment groups. Treatment groups will define the message texts, number of messages, and when to send the messages. Patients in an experiment will not receive the standard missed visit reminder that is sent three days after a scheduled appointment. Control group patients will receive no messages at all.
```

trying to clarify this point

2021-06-15 22:06 UTC, rsanheim commented on doc/arch/016-ab-testing.md
> +- is not in an ongoing experiment or one that ended within the past 14 days.
```suggestion
- is not in an ongoing experiment or one that ended recently
```

less about implementation, more about the intention

2021-06-17 20:13 UTC, kpethtel commented on doc/arch/016-ab-testing.md
> +## Consequences
Valid points, especially re: rate limits. I'll work on it.

2021-07-28 09:18 UTC, harimohanraj89 approved these changes
I like the separation of the ADR and the how-to wiki doc. Let's get this merged.

2021-07-29 02:32 UTC, merged