Feature flag drug stock for districts instead of users
simpledotorg/simple-server pull request #2597
Opened 2021-06-14 11:36 UTC by prabhanshuguptagit

**Story card:** [ch3321](https://app.clubhouse.io/simpledotorg/story/3321)

## Because

We want to enable drug stocks for a district at a time, instead of enabling on a per user basis.

## This addresses

Adds `Region` as a flipper actor and feature flags the drug stocks pages based on it.

2021-06-24 09:30 UTC, harimohanraj89 requested changes
Looks great, can we add the relevant test coverage to this PR?

2021-07-06 11:45 UTC, prabhanshuguptagit commented
Did some refactoring, ready for re-review @harimohanraj89.

2021-07-12 12:12 UTC, harimohanraj89 commented on spec/models/user_spec.rb
> +    it "is true if any district accessible by the user is enabled" do
I'd love to one more spec that flips on a facility _outside_ the admin's access, and ensures the result is false.

2021-07-12 12:14 UTC, harimohanraj89 commented on spec/models/region_spec.rb
> +    it "has feature_enabled?" do
Could we add more sad path coverage?

```ruby
describe "#feature_enabled?" do
  it "returns true when feature is enabled for region"
  it "returns false when feature is disabled for region"
end
```

2021-07-12 14:52 UTC, harimohanraj89 approved these changes
So sad path. :shipit:

2021-07-13 13:21 UTC, merged