Add translations for missed visits in the progress tab
simpledotorg/simple-server pull request #4112
Opened 2022-06-27 12:49 UTC by govindkrjoshi

**Story card:** [sc-XXXX](URL)

## Because

Enter the reason for raising this PR...

## This addresses

Enter the details of what all this covers...

## Test instructions

Enter detailed instructions for how to test this PR...

2022-06-27 13:14 UTC, PriyangaPKini approved these changes
lgtm👍🏻

2022-06-28 09:23 UTC, harimohanraj89 requested changes
Blocking review.

2022-06-28 09:23 UTC, harimohanraj89 commented on config/locales/api/am_ET.yml
> +am_ET:
IIRC, this key should not change. It should remain hyphenated. Let's revert this diff. 

Transifex annoyingly makes this diff every time ([documented here](https://github.com/simpledotorg/simple-server/blob/master/doc/wiki/transifex-localization.md#3-check-and-fix-all-top-level-language-keys))

2022-06-28 10:06 UTC, harimohanraj89 approved these changes
:shipit:

2022-06-29 06:41 UTC, merged