Show old progress tab for app version before '2022-07-04-8318'
simpledotorg/simple-server pull request #4630
Opened 2022-12-06 12:38 UTC by PriyangaPKini

**Story card:** [sc-9741](https://app.shortcut.com/simpledotorg/story/9741/show-old-progress-tab-when-app-version-2022-07-04-8318)

## Because

APP versions < '2022-07-04-8318' crashes when rendering the new progress tab.

## This addresses

Show the old progress tab for APP version < '2022-07-04-8318'

## Test instructions

#### Setup
- Use postman/mod header to pass additional headers. You will need to pass these headers below
  - `X-USER-ID`,  `X-Facility-ID`, `Authorization`. Use `rails get_user_crendentials` to get the values for these headers locally
- Goto `http://localhost:3000/api/v3/analytics/user_analytics.html#`
- Add the header `HTTP-X-APP-VERSION`:  `2022-06-04-8318`. You should see the old progress tab
- Add the header `HTTP-X-APP-VERSION`:  `2022-07-04-8318`. You should see the new progress tab

2022-12-07 04:04 UTC, harimohanraj89 requested changes
Some feedbacks

2022-12-07 06:43 UTC, PriyangaPKini commented on app/controllers/api/v3/analytics/user_analytics_controller.rb
> +  APP_OLD_VERSION_RELEASE_DATE = "2022-07-04"
Hmm, that make sense.

2022-12-07 06:44 UTC, PriyangaPKini commented on app/controllers/api/v3/analytics/user_analytics_controller.rb
> +      (Flipper.enabled?(:new_progress_tab_v2, current_user) || Flipper.enabled?(:new_progress_tab_v2))
Oh no. Will fix this

2022-12-07 06:46 UTC, PriyangaPKini commented on app/controllers/api/v3/analytics/user_analytics_controller.rb
> +    app_version = request.headers["HTTP-X-APP-VERSION"] || "" # Default to old progress tab when app version is nil
That's a good point. I'll do this way

2022-12-07 06:48 UTC, harimohanraj89 commented on app/controllers/api/v3/analytics/user_analytics_controller.rb
> +      (Flipper.enabled?(:new_progress_tab_v2, current_user) || Flipper.enabled?(:new_progress_tab_v2))
No worries! It was still working as intended before 👍

2022-12-07 06:56 UTC, PriyangaPKini commented on app/controllers/api/v3/analytics/user_analytics_controller.rb
> +      (Flipper.enabled?(:new_progress_tab_v2, current_user) || Flipper.enabled?(:new_progress_tab_v2))
I have done this mistake in more places, I will fix that too in a separate PR

2022-12-08 10:50 UTC, PriyangaPKini commented on app/controllers/api/v3/analytics/user_analytics_controller.rb
>          format.html { render :show }
Show "Update required" instead of old progress tab

2022-12-08 14:02 UTC, jamiecarter7 commented
Implemented 'update app' card:
- card design
- translation strings
please check I've done this all correctly as I am unable to test on localhost now the app version thing has been implemented

2022-12-09 08:15 UTC, prabhanshuguptagit approved these changes

2022-12-09 08:15 UTC, prabhanshuguptagit commented on app/views/api/v3/analytics/user_analytics/progress_update_required.html.erb
> +<%= inline_js("standalone/user_analytics.js") %>
Think this view doesn't need to include the JS.

2022-12-09 08:16 UTC, PriyangaPKini commented on app/controllers/api/v3/analytics/user_analytics_controller.rb
>          format.html { render :show }
Show the **_old progress tab_** when `new_progress_tab` is disabled (In Ethiopia and Srilanka)
Show **_"Update Required"_** when `new_progress_tab` is enabled and `app version < min_app_version`
Show the **_new progress tab_** when `new_progress_tab` is enabled and `app version >= min_app_version`

2022-12-09 12:48 UTC, merged