[DRAFT] sc-13986 Enabled diabetes option in progress tab
simpledotorg/simple-server pull request #5481
Opened 2024-11-08 11:13 UTC by Gyan-Gupta-Rtsl

**Story card:** [sc-13986](https://app.shortcut.com/simpledotorg/story/13986/enable-diabetes-option-in-progress-tab)

## Because
Enabled the diabetes option with the assigned patients section

## This addresses
Enabled the patients section 

## Test instructions

2024-11-12 11:55 UTC, Gyan-Gupta-Rtsl commented
Without flipper flag:

<img width="1510" alt="Screenshot 2024-11-12 at 5 23 20 PM" src="https://github.com/user-attachments/assets/be126e7d-8ba5-4551-adce-71493eb11b7e">

With Flipper flag:
<img width="1511" alt="Screenshot 2024-11-08 at 9 02 51 PM" src="https://github.com/user-attachments/assets/8318ead7-6301-46da-aca7-545880aa39ac">
<img width="1512" alt="Screenshot 2024-11-08 at 9 03 13 PM" src="https://github.com/user-attachments/assets/13463e00-d751-4f38-8317-fcebce97e105">

2024-11-13 11:31 UTC, danySam requested changes
Looks ready! 

I’d suggest adding the details of the flipper flag to `⁠/docs/wiki/feature-flags.md`. We capture the details of the feature flags there. 

Also, in your PR’s title and description, you can mention that this only implements assigned patients. At first, I was under the assumption that this would include all the necessary changes for the diabetes progress report.

2024-11-14 07:49 UTC, Gyan-Gupta-Rtsl commented
@danySam Can you review this PR.

2024-11-14 07:56 UTC, danySam commented on doc/wiki/feature-flags.md
> +| diabetes_progress_report_tab				| Yes						   | When the progress tab is activated, the diabetes section will be displayed as enabled, followed by a comprehensive listing of all associated key indi
```suggestion
| diabetes_who_standard_indicator           | Yes                          | When enabled, only FBS and HBA1c measurements are considered for calculating diabetes controlled and uncontrolled rate
| diabetes_progress_report_tab		    | Yes	    		      | When the progress tab is activated, the diabetes section will be displayed as enabled, followed by a comprehensive listing of all associated key indicators.
```

2024-11-14 07:58 UTC, danySam commented on doc/wiki/feature-flags.md
> +| diabetes_progress_report_tab				| Yes						   | When the progress tab is activated, the diabetes section will be displayed as enabled, followed by a comprehensive listing of all associated key indi
```suggestion
| diabetes_progress_report_tab				| Yes						   | When the progress tab is activated, the diabetes section will be displayed as enabled, followed by a comprehensive listing of all associated key indicators.
```

2024-11-14 13:01 UTC, danySam approved these changes

2024-11-15 06:54 UTC, merged